# Generated by Django 4.1.2 on 2023-02-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='artist_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
